# Generated by Django 3.2.2 on 2021-11-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Компания:')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя:')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия:')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail:')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=6, verbose_name='Закуплно:')),
                ('red', models.CharField(max_length=6, verbose_name='Ошибки:')),
                ('green', models.CharField(max_length=6, verbose_name='Работает:')),
                ('grey', models.CharField(max_length=6, verbose_name='Серые:')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата:')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='license.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
